// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node
    command:
    - sleep
    args:
    - infinity
 
'''
            defaultContainer 'node'
        }
    }
    
    stages {
        stage('Build') {
            steps ('Install dependencies'){
                dir('./hello-world-nodejs'){
                sh 'npm i'
            }
            }
        }
        stage('Run unit tests'){
            steps {
                dir('./hello-world-nodejs'){
                sh 'npm run test testRoutes.py'
            }
            }
        }
        stage('Generate artifact'){
            steps {
                dir('./hello-world-nodejs'){
                sh 'ls -lha'
                sh 'pwd'
                sh 'mkdir artifacts'
                sh "tar -czvf artifacts/nodejs-app:${env.BUILD_ID}.tar.gz ."
            }
            }
        }
    }
}
